migrations = [
    ("sells",   "vendedor",       "TEXT NOT NULL DEFAULT 'unknown'"),
    ("sells",   "payment_method", "TEXT NOT NULL DEFAULT 'Efectivo'"),
    ("details", "vendedor",       "TEXT NOT NULL DEFAULT 'unknown'"),
    ("details", "payment_method", "TEXT NOT NULL DEFAULT 'Efectivo'"),
    ("users",   "status",         "INTEGER NOT NULL DEFAULT 1"),
    ("users",   "created_at",     "TEXT DEFAULT NULL"),
    ("sells",   "date",           "TEXT NOT NULL"),
    ("items", "expiration_date", "TEXT"),
    ("items", "id", "INTEGER PRIMARY KEY NOT NULL"),
    ("items", "notified_low_stock", "INTEGER NOT NULL DEFAULT 0"),
    ("items", "created_at", "TEXT"),
    ("items", "updated_at", "TEXT"),
    ("sells",   "vendor_id",       "INTEGER DEFAULT NULL"),
    ("details", "vendor_id",       "INTEGER DEFAULT NULL"),
    ("users",   "history",         "TEXT"),
    ("users",   "application",     "TEXT NOT NULL DEFAULT 'accepted'"),
    ("users", "application", "TEXT NOT NULL DEFAULT 'accepted'"),
    ("users", "username", "TEXT NOT NULL"),
    ("users", "id", "INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE"),
    ("users", "email", "TEXT NOT NULL UNIQUE"),
    ("sells", "customer_id", "INTEGER DEFAULT NULL"),
    ("sells", "amount_paid", "REAL DEFAULT NULL"),
    ("sells", "customer_id",  "INTEGER DEFAULT NULL"),
    ("sells", "amount_paid",  "REAL DEFAULT NULL"),
]